// <auto-generated />
using System;
using HiloGame.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiloGame.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiloGame.Domain.Models.GameState", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("GuessCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGameOver")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGameWon")
                        .HasColumnType("boolean");

                    b.Property<int>("MysteryNumber")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HiloGame.Domain.Models.GameState", b =>
                {
                    b.OwnsOne("HiloGame.Domain.Models.GameRange", "Range", b1 =>
                        {
                            b1.Property<Guid>("GameStateGameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxValue")
                                .HasColumnType("integer")
                                .HasColumnName("MaxRange");

                            b1.Property<int>("MinValue")
                                .HasColumnType("integer")
                                .HasColumnName("MinRange");

                            b1.HasKey("GameStateGameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameStateGameId");
                        });

                    b.Navigation("Range")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
